/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.BCNumberOfTreasures;
import Model.BCSpecificTreasures;
import Model.BadConsequence;

/**
 *
 * @author xehartnort
 */
public class BadConsequenceView extends javax.swing.JPanel {

    
    private BadConsequence badConsequenceModel;
    /**
     * Creates new form BadConsequenceView
     */
    public BadConsequenceView() {
        initComponents();
    }
    
    public void setBadConsequence(BadConsequence b){
        this.badConsequenceModel = b;
        this.text.setText(badConsequenceModel.getText());
        this.levels.setText(Integer.toString(badConsequenceModel.getLevels()));

        this.specificVisibleTreasures.setEnabled(false);
        this.specificHiddenTreasures.setEnabled(false);
        this.nVisibleTreasures.setEnabled(false);
        this.nHiddenTreasures.setEnabled(false);
        
        if( badConsequenceModel instanceof BCNumberOfTreasures )
        {
            this.nVisibleTreasures.setEnabled(true);
            this.nHiddenTreasures.setEnabled(true);
            this.nVisibleTreasures.setText( Integer.toString(
                ((BCNumberOfTreasures)badConsequenceModel).getNVisibleTreasures())
                                          );
            this.nHiddenTreasures.setText( Integer.toString(
                ((BCNumberOfTreasures)badConsequenceModel).getNHiddenTreasures())
                                          );
        }else if ( badConsequenceModel instanceof BCSpecificTreasures ) 
        {
            this.specificVisibleTreasures.setEnabled(true);
            this.specificHiddenTreasures.setEnabled(true);       
//            TODO I really dont know what should i do here, am i mad?
//            this.specificVisibleTreasures = ((BCSpecificTreasures)badConsequenceModel).getSpecificVisibleTreasures();
//            fillTreasurePanel (specificHiddenTreasures, ((BCSpecificTreasures)badConsequenceModel).getSpecificHiddenTreasures());
        }
    }

//        public void fillTreasurePanel (JPanel aPanel, ArrayList<TreasureKind> aList) {
//        // Se recorre la lista de tesoros construyendo y añadiendo sus vistas
//        // al panel
//        for (TreasureKind t : aList) {
//            aPanel.add(t);
//        }
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        levels = new javax.swing.JLabel();
        death = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nVisibleTreasures = new javax.swing.JLabel();
        nHiddenTreasures = new javax.swing.JLabel();
        specificVisibleTreasures = new javax.swing.JPanel();
        specificHiddenTreasures = new javax.swing.JPanel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        text.setText("Text");

        levels.setText("Levels");

        death.setText("Death");

        nVisibleTreasures.setText("Number Of Visible Treasures");

        nHiddenTreasures.setText("Number Of Hidden Treasures");

        specificVisibleTreasures.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout specificVisibleTreasuresLayout = new javax.swing.GroupLayout(specificVisibleTreasures);
        specificVisibleTreasures.setLayout(specificVisibleTreasuresLayout);
        specificVisibleTreasuresLayout.setHorizontalGroup(
            specificVisibleTreasuresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        specificVisibleTreasuresLayout.setVerticalGroup(
            specificVisibleTreasuresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        specificHiddenTreasures.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout specificHiddenTreasuresLayout = new javax.swing.GroupLayout(specificHiddenTreasures);
        specificHiddenTreasures.setLayout(specificHiddenTreasuresLayout);
        specificHiddenTreasuresLayout.setHorizontalGroup(
            specificHiddenTreasuresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        specificHiddenTreasuresLayout.setVerticalGroup(
            specificHiddenTreasuresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(text)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(levels)
                        .addContainerGap())
                    .addComponent(nVisibleTreasures)
                    .addComponent(specificVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(specificHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(death))
                        .addComponent(nHiddenTreasures))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text)
                    .addComponent(levels))
                .addGap(23, 23, 23)
                .addComponent(nVisibleTreasures)
                .addGap(3, 3, 3)
                .addComponent(specificVisibleTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(nHiddenTreasures)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(specificHiddenTreasures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(death, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel death;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel levels;
    private javax.swing.JLabel nHiddenTreasures;
    private javax.swing.JLabel nVisibleTreasures;
    private javax.swing.JPanel specificHiddenTreasures;
    private javax.swing.JPanel specificVisibleTreasures;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
