/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Treasure;
import java.awt.Color;

/**
 *
 * @author Salva
 */
public class TreasureView extends javax.swing.JPanel {

    private boolean selected = false;
    private Treasure treasureModel;
    /**
     * Creates new form newTreasureView
     */
    public TreasureView() {
        initComponents();
    }

    public void setTreasure(Treasure t){
        this.treasureModel = t;
        this.name.setText(treasureModel.getName());
        this.coins.setText(Integer.toString(treasureModel.getGoldCoins())+" €"); 
        this.maxBonus.setText(Integer.toString(treasureModel.getSpecialValue())); 
        this.minBonus.setText(Integer.toString(treasureModel.getBasicValue()));
        switch (t.getType())
        {
            case ARMOR:
                this.type.setText("Armadura");
                break;
            case ONEHAND:
                this.type.setText("Una mano");
                break;
            case BOTHHANDS:
                this.type.setText("De dos Manos");
                break;
            case HELMET:
                this.type.setText("Casco");
                break;
            case SHOE:
                this.type.setText("Calzado");
                break;
            case NECKLACE:
        }
        this.repaint();   
    }
    
    public boolean isSelected ()
    {
        return selected;
    }
    
    public Treasure getTreasure()
    {
        return treasureModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        coins = new javax.swing.JLabel();
        maxBonus = new javax.swing.JLabel();
        minBonus = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        type = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        coins.setText("Coins");

        maxBonus.setText("Level max.");

        minBonus.setText("Level min.");

        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Name");

        type.setText("Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(minBonus)
                        .addComponent(maxBonus)
                        .addComponent(coins)
                        .addComponent(type)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coins)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maxBonus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(minBonus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        Color c;
        if(selected)
            c = Color.gray;//Color Gris
        else 
            c = new Color(240,240,240);//Color original
        this.setBackground(c);//Cambio el color
        this.repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel coins;
    private javax.swing.JLabel maxBonus;
    private javax.swing.JLabel minBonus;
    private javax.swing.JLabel name;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
